package com.app.cutoff.data.database.entity;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * One row per half-month cutoff period (e.g. "July 1-15", "July 16-31").
 * Auto-generated by CutoffRepository based on the current date — never
 * created manually by the user. Salary is snapshotted at creation time so
 * later salary edits don't rewrite history.
 */
@Entity(tableName = "cutoff")
public class CutoffEntity {

    @PrimaryKey(autoGenerate = true)
    private long id;

    private long periodStartEpochDay; // inclusive, java.time.LocalDate.toEpochDay()
    private long periodEndEpochDay;   // inclusive
    private double salarySnapshot;    // salary that applied when this cutoff was generated

    public CutoffEntity(long periodStartEpochDay, long periodEndEpochDay, double salarySnapshot) {
        this.periodStartEpochDay = periodStartEpochDay;
        this.periodEndEpochDay = periodEndEpochDay;
        this.salarySnapshot = salarySnapshot;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getPeriodStartEpochDay() {
        return periodStartEpochDay;
    }

    public void setPeriodStartEpochDay(long periodStartEpochDay) {
        this.periodStartEpochDay = periodStartEpochDay;
    }

    public long getPeriodEndEpochDay() {
        return periodEndEpochDay;
    }

    public void setPeriodEndEpochDay(long periodEndEpochDay) {
        this.periodEndEpochDay = periodEndEpochDay;
    }

    public double getSalarySnapshot() {
        return salarySnapshot;
    }

    public void setSalarySnapshot(double salarySnapshot) {
        this.salarySnapshot = salarySnapshot;
    }
}
